require: rubocop-rspec

AllCops:
  Exclude:
      - 'db/schema.rb'
      - 'bin/*'
      - 'vendor/**/*'

Metrics/ClassLength:
  Max: 250

Metrics/LineLength:
  Max: 199

Metrics/MethodLength:
  Max: 30

Rails:
  Enabled: true

Style/BlockComments:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Layout/SpaceInsideBrackets:
  Enabled: false

Style/StringLiterals:
  Enabled: false
