Style/Encoding:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/LeadingCommentSpace:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Metrics/LineLength:
  Max: 199

Style/NumericLiterals:
  Enabled: false
