Style/Encoding:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockComments:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/SpaceInsideBrackets:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Metrics/LineLength:
  Max: 199

Style/NumericLiterals:
  Enabled: false
