version: '3.3'
services:
  postgres:
    image: mdillon/postgis:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  hubzone-api:
    build:
      context: .
      cache_from:
      - hubzone/hubzone-api:latest
    image: hubzone/hubzone-api:latest
    restart: always
    links:
      - postgres
    env_file:
      - ./docker/hubzone-api.env
    ports:
      - '3001:3001'
    command: >
      /bin/bash -c "
        function waitfor() {
          while ! nc -z $$1 $$2;
          do
            echo waiting for $$1;
            sleep 3;
          done;
          echo Connected to $$1!;
        }

        waitfor postgres 5432;

        start-rails.sh;
        echo rails process exited, stopping container.;
      "
