version: '3.3'
services:

  postgres:
    image: postgis/postgis:12-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hzgeo

  hubzone-api:
    build:
      context: .
      #cache_from:
      #- hubzone/hubzone-api:latest
    image: hubzone/hubzone-api:latest
    environment:
      RAILS_ENV: developmentdocker
      HUBZONE_API_DB_USER: postgres
      HUBZONE_API_DB_PASSWORD: postgres
      HUBZONE_API_DB_HOST: postgres
      HUBZONE_API_DB_NAME: hzgeo
      SECRET_KEY_BASE: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      HUBZONE_GOOGLE_API_KEY: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      # OVERRIDE VARS
      # ---------------------------------------------
      # PORT: 3001
      # RAILS_LOG_TO_STDOUT: "true"
      # RAILS_MAX_THREADS: 5
    ports:
      - 3001:3001
    command: >
      /bin/bash -c "
        function waitfor() {
          while ! nc -z $$1 $$2;
          do
            echo waiting for $$1;
            sleep 3;
          done;
          echo Connected to $$1!;
        }
        waitfor postgres 5432;
        start-rails.sh;
        echo rails process exited, stopping container.;
      "
