# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2

executors:
  ruby:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          RAILS_ENV: test
  ruby-with-postgres:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          HUBZONE_API_DB_USER: postgres
          HUBZONE_API_DB_PASSWORD: postgres
          RAILS_ENV: test
      - image: circleci/postgres:9.6-alpine-postgis
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

commands:
  install-system-dependencies:
    steps:
      - run:
          name: Install system dependencies
          command: |
            sudo apt update
            sudo apt install -y \
              postgresql-client-9.6
  install-and-cache-gems:
    steps:
      - checkout
      - ruby/install-deps:
          key: gems-v1
      #- run: sudo npm install -g istanbul
  migrate-db:
    steps:
      - run:
          name: migrate-db
          command: |
            bundle exec rake db:create db:migrate
workflows:
  version: 2
  test:
    jobs:
      - rubocop
      - rspec
      - rspec-docker
      - brakeman
jobs:
  rubocop:
    executor: ruby
    steps:
      - install-system-dependencies
      - install-and-cache-gems
      - ruby/rubocop-check
  rspec:
    executor: ruby-with-postgres
    steps:
      - install-system-dependencies
      - install-and-cache-gems
      - migrate-db
      - run:
          name: Run rspec
          command: bundle exec rspec --format progress
  rspec-docker:
    executor: ruby
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Build rspec in Docker container
        command: |
          git describe --long > REVISION || touch REVISION
          cat REVISION
          docker-compose -f docker/docker-compose-test.yml build rspec
    - run:
        name: Run rspec in Docker container
        command: |
          docker-compose -f docker/docker-compose-test.yml run rspec

  brakeman:
    executor: ruby
    steps:
      - install-system-dependencies
      - install-and-cache-gems
      - run:
          name: brakeman
          parallel: true
          command: |
            gem install --no-document brakeman
            brakeman --exit-on-warn .
