version: '3.2'
services:
  postgres:
    image: mdillon/postgis:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  rspec:
    build:
      context: ..
      cache_from:
      - hubzone/hubzone-api:latest
    image: hubzone/hubzone-api:latest
    links:
      - postgres
    #env_file:
    #  - hubzone-api.env
    #  - hubzone-api-test.env
    environment:
      - RAILS_ENV=test
      - RAILS_LOG_TO_STDOUT=true
      - HUBZONE_API_DB_USER=postgres
      - HUBZONE_API_DB_PASSWORD=postgres
      - HUBZONE_API_DB_HOST=postgres
      - SECRET_KEY_BASE=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      - HUBZONE_GOOGLE_API_KEY='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
    entrypoint: ["/bin/bash"]
    command: >
      -c "
        while ! nc -z postgres 5432;
        do
          echo waiting for postgres;
          sleep 1;
        done;
        echo Connected to postgres!;
        bundle exec rake db:create db:migrate &&
        bundle exec rspec spec;
      "
