name: 'ECR'
description: 'Build, tag and push Docker images to ECR'

inputs:
  dockerfile:
    default: 'Dockerfile'
    description: 'Relative path from the project root to the Dockerfile.'
    required: false

  image:
    description: 'Complete ECR name including both the account number and region.'
    required: true

  push_to_ecr:
    default: true
    description: 'Whether or not the image will be pushed to ECR considering the build was successful.'
    required: false

runs:
  using: 'composite'
  steps:
    - shell: 'bash'
      run: |
        cd `dirname ${{ inputs.dockerfile }}`
        docker image pull ${{ inputs.image }}:latest || true
        docker image build --pull --cache-from=${{ inputs.image }}:latest . -f `basename ${{ inputs.dockerfile }}` -t ${{ inputs.image }}:latest
        if [[ '${{ inputs.push_to_ecr }}' == 'true' ]]; then
          docker image push ${{ inputs.image }}:latest
          docker image tag ${{ inputs.image }}:latest ${{ inputs.image }}:${GITHUB_SHA}
          docker image push ${{ inputs.image }}:${GITHUB_SHA}
        fi
