#
# This file configures the New Relic Agent.  New Relic monitors Ruby, Java,
# .NET, PHP, Python and Node applications with deep visibility and low
# overhead.  For more information, visit www.newrelic.com.
#
# Generated October 20, 2017
#
# This configuration file is custom generated for SBA_4
#
# For full documentation of agent configuration options, please refer to
# https://docs.newrelic.com/docs/agents/ruby-agent/installation-configuration/ruby-agent-configuration

common: &default_settings
  # Required license key associated with your New Relic account.
  license_key: c617ad484fad13bd5216be46582d5a80fd23af9f

  # Your application name. Renaming here affects where data displays in New
  # Relic.  For more details, see https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/renaming-applications
  app_name: HUBZone API

  # To disable the agent regardless of other settings, uncomment the following:
  # agent_enabled: false

  # Logging level for log/newrelic_agent.log
  log_level: info

  # When true, the agent transmits data about your app to the New Relic collector.
  # By default, we will have this turned off, and turn it on only for the environments
  # in which we actually want to collect data (i.e., only in production)
  monitor_mode: false

# Environment-specific settings are in this section.
# RAILS_ENV or RACK_ENV (as appropriate) is used to determine the environment.
# If your application has other named environments, configure them here.
production:
  <<: *default_settings
  app_name: hz-prod-api
  monitor_mode: true

staging:
  <<: *default_settings
  app_name: hz-stg-api

demo:
  <<: *default_settings
  app_name: hz-demo-api

dev:
  <<: *default_settings
  app_name: hz-dev-api

development:
  <<: *default_settings
  app_name: hz-local-api

test:
  <<: *default_settings
